[[main]]
  name = "Einsätze"
  pageRef = "einsaetze/"
  weight = 1

[[main]]
  name = "2025"
  parent = "Einsätze"
  pageRef = "einsaetze/2025/"
  weight = 2

[[main]]
  name = "2024"
  parent = "Einsätze"
  pageRef = "einsaetze/2024/"
  weight = 3

[[main]]
  name = "2023"
  parent = "Einsätze"
  pageRef = "einsaetze/2023/"
  weight = 4

[[main]]
  name = "2022"
  parent = "Einsätze"
  pageRef = "einsaetze/2022/"
  weight = 5

[[main]]
  name = "2021"
  parent = "Einsätze"
  pageRef = "einsaetze/2021/"
  weight = 6

[[main]]
  name = "2020"
  parent = "Einsätze"
  pageRef = "einsaetze/2020/"
  weight = 7

[[main]]
  name = "2019"
  parent = "Einsätze"
  pageRef = "einsaetze/2019/"
  weight = 8

[[main]]
  name = "2018"
  parent = "Einsätze"
  pageRef = "einsaetze/2018/"
  weight = 9

[[main]]
  name = "Aktuelles"
  pageRef = "aktuelles/"
  weight = 20

[[main]]
  name = "Förderverein"
  pageRef = "foerderverein/"
  weight = 30

[[main]]
  name = "Über uns"
  weight = 40

[[main]]
  name = "Feuerwehrhaus"
  parent = "Über uns"
  pageRef = "feuerwehrhaus/"
  weight = 1

[[main]]
  name = "Fahrzeuge"
  parent = "Über uns"
  pageRef = "fahrzeuge/"
  weight = 10

[[main]]
  name = "Ehemalige Fahrzeuge"
  parent = "Über uns"
  pageRef = "ehemalige/"
  weight = 20

[[main]]
  name = "Mitmachen"
  parent = "Über uns"
  pageRef = "mitmachen/"
  weight = 40

[[main]]
  name = "Kontakt"
  parent = "Über uns"
  pageRef = "kontakt/"
  weight = 50

#[[main]]
#  name = "Tags"
#  pageRef = "/tags"
#  weight = 20

[[social]]
  name = "Facebook"
  pre = "fab facebook"
  url = "https://www.facebook.com/feuerwehrhamburgeppendorf"
  weight = 1

[[social]]
  name = "Instagram"
  pre = "fab instagram"
  url = "https://www.instagram.com/feuerwehrhamburgeppendorf/"
  weight = 10

# [[social]]
#   name = "Twitter"
#   pre = "fab x-twitter"
#   url = "https://twitter.com/FFEppendorf/"
#   weight = 20

[[footer]]
  name = "Links"
  weight = 10

[[footer]]
  parent = "Links"
  name = "Impressum"
  pageRef = "impressum"
  weight = 1

[[footer]]
  parent = "Links"
  name = "Datenschutz"
  pageRef = "datenschutz"
  weight = 2

[[footer]]
  parent = "Links"
  name = "Kontakt"
  pageRef = "kontakt"
  weight = 3
